server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  context-path: /boot
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_Spring_Boot?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org.springframework.web: ERROR
    cn.zsza: info


